[package]
name = "manager"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
get_if_addrs = { version = "0.5.3" }
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
chrono = { version = "0.4.41" }