[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", features = ["node"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
