name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-document:
    defaults:
      run:
        working-directory: ./manager
    timeout-minutes: 3
    name: Build a document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Build document
        run: cargo doc --document-private-items --all --open --lib --bins --all-features --no-deps
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./target/doc
          token: ${{ secrets.GITHUB_TOKEN }}

  actions-timeline:
    needs:
      - deploy-document
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2